
/**************************************************************
 *	
 *	clang, 8 bit, 11025Hz,
 *	1 channel, 17243 bytes/channel
 *	Total Size: 1 * 17243 + 4 (header) = 17287 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sarah Tsai\Documents\cs2261\M04\clang.wav
 *	Time-stamp: Thu Nov 29 14:58:54 2018
 *	
 **************************************************************/

#ifndef __CLANGH__
#define __CLANGH__

#define CLANGFREQ 11025
#define CLANGLEN 17243

extern const unsigned char clang[17243];

#endif /* __CLANGH__ */
