
/**************************************************************
 *	
 *	MegaHyperUltrastorm, 8 bit, 11025Hz,
 *	1 channel, 2129472 bytes/channel
 *	Total Size: 1 * 2129472 + 4 (header) = 2129516 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sarah Tsai\Documents\cs2261\M04\MegaHyperUltrastorm.wav
 *	Time-stamp: Thu Nov 29 14:58:16 2018
 *	
 **************************************************************/

#ifndef __MEGAHYPERULTRASTORMH__
#define __MEGAHYPERULTRASTORMH__

#define MEGAHYPERULTRASTORMFREQ 11025
#define MEGAHYPERULTRASTORMLEN 2129472

extern const unsigned char MegaHyperUltrastorm[2129472];

#endif /* __MEGAHYPERULTRASTORMH__ */
