
/**************************************************************
 *	
 *	quack, 8 bit, 11025Hz,
 *	1 channel, 1543 bytes/channel
 *	Total Size: 1 * 1543 + 4 (header) = 1587 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sarah Tsai\Documents\cs2261\M05\quack.wav
 *	Time-stamp: Tue Dec 04 14:38:57 2018
 *	
 **************************************************************/

#ifndef __QUACKH__
#define __QUACKH__

#define QUACKFREQ 11025
#define QUACKLEN 1543

extern const unsigned char quack[1543];

#endif /* __QUACKH__ */
