
/**************************************************************
 *	
 *	SpringBreak, 8 bit, 11025Hz,
 *	1 channel, 2648160 bytes/channel
 *	Total Size: 1 * 2648160 + 4 (header) = 2648204 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sarah Tsai\Documents\cs2261\M04\SpringBreak.wav
 *	Time-stamp: Thu Nov 29 14:58:39 2018
 *	
 **************************************************************/

#ifndef __SPRINGBREAKH__
#define __SPRINGBREAKH__

#define SPRINGBREAKFREQ 11025
#define SPRINGBREAKLEN 2648160

extern const unsigned char SpringBreak[2648160];

#endif /* __SPRINGBREAKH__ */
