
/**************************************************************
 *	
 *	swish, 8 bit, 11025Hz,
 *	1 channel, 5920 bytes/channel
 *	Total Size: 1 * 5920 + 4 (header) = 5964 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sarah Tsai\Documents\cs2261\M04\swish.wav
 *	Time-stamp: Thu Nov 29 14:58:26 2018
 *	
 **************************************************************/

#ifndef __SWISHH__
#define __SWISHH__

#define SWISHFREQ 11025
#define SWISHLEN 5920

extern const unsigned char swish[5920];

#endif /* __SWISHH__ */
