
/**************************************************************
 *	
 *	VacationWasteland, 8 bit, 11025Hz,
 *	1 channel, 2404800 bytes/channel
 *	Total Size: 1 * 2404800 + 4 (header) = 2404844 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sarah Tsai\Documents\cs2261\M04\VacationWasteland.wav
 *	Time-stamp: Thu Nov 29 14:50:21 2018
 *	
 **************************************************************/

#ifndef __VACATIONWASTELANDH__
#define __VACATIONWASTELANDH__

#define VACATIONWASTELANDFREQ 11025
#define VACATIONWASTELANDLEN 2404800

extern const unsigned char VacationWasteland[2404800];

#endif /* __VACATIONWASTELANDH__ */
